table 'Operações contratadas'
	lineageTag: 78efb7a9-381f-41e6-b447-c55313f84656

	column Column1
		dataType: string
		lineageTag: dd502679-6b26-4ece-bb3d-d432dd2debb4
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column 'Compra - Bancário - Valor USD (milhares)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0e7f3d9d-dad3-48e4-b451-9729cabfb480
		summarizeBy: sum
		sourceColumn: Compra - Bancário - Valor USD (milhares)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Venda - Bancário - Valor USD (milhares)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: cc69bc64-761c-4ead-946f-5d5c8cfad560
		summarizeBy: sum
		sourceColumn: Venda - Bancário - Valor USD (milhares)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Compra - Não Bancário - Valor USD (milhares)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: d046a5a7-0a5b-4882-943c-7720801a89f0
		summarizeBy: sum
		sourceColumn: Compra - Não Bancário - Valor USD (milhares)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Venda - Não Bancário - Valor USD (milhares)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a43c178f-bad2-4e21-84f0-fb4c11da9b54
		summarizeBy: sum
		sourceColumn: Venda - Não Bancário - Valor USD (milhares)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Total - Valor USD (milhares)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: d77268e2-8259-423e-802b-564c6875f969
		summarizeBy: sum
		sourceColumn: Total - Valor USD (milhares)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column '% Acumul'
		dataType: string
		lineageTag: d9ce60a5-1387-4610-83c8-51fd772d24c2
		summarizeBy: none
		sourceColumn: % Acumul

		annotation SummarizationSetBy = Automatic

	partition 'Operações contratadas' = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\Users\breno\OneDrive\Base de dados Bi\Fonte Dolar"),
				    #"C:\Users\breno\OneDrive\Base de dados Bi\Fonte Dolar\_2-FEME 2025-1 csv" = Fonte{[#"Folder Path"="C:\Users\breno\OneDrive\Base de dados Bi\Fonte Dolar\",Name="2-FEME.2025-1.csv"]}[Content],
				    #"CSV Importado" = Csv.Document(#"C:\Users\breno\OneDrive\Base de dados Bi\Fonte Dolar\_2-FEME 2025-1 csv",[Delimiter=";", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"CSV Importado",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Column3] <> "")),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Filtradas", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Descrição", type text}, {"", type text}, {"Compra - Bancário", type text}, {"_1", type text}, {"Venda - Bancário", type text}, {"_2", type text}, {"Compra - Não Bancário", type text}, {"_3", type text}, {"Venda - Não Bancário", type text}, {"_4", type text}, {"Total", type text}, {"_5", type text}, {"% Acumul", type text}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado1", each ([Descrição] <> "")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas1",{"Descrição", "_1", "_2", "_3", "_4", "_5"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas",{{"Compra - Bancário", "Compra - Bancário - Valor USD (milhares)"}, {"Venda - Bancário", "Venda - Bancário - Valor USD (milhares)"}, {"Compra - Não Bancário", "Compra - Não Bancário - Valor USD (milhares)"}, {"Venda - Não Bancário", "Venda - Não Bancário - Valor USD (milhares)"}, {"Total", "Total - Valor USD (milhares)"}}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Colunas Renomeadas", each ([#""] <> "")),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Linhas Filtradas2",{{"Total - Valor USD (milhares)", Currency.Type}, {"Venda - Não Bancário - Valor USD (milhares)", Currency.Type}, {"Compra - Não Bancário - Valor USD (milhares)", Currency.Type}, {"Venda - Bancário - Valor USD (milhares)", Currency.Type}, {"Compra - Bancário - Valor USD (milhares)", Currency.Type}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

